docs: update code of conduct
thepurplebubble/protocol pull request #5
Opened 2023-12-13 21:06 UTC by kcoderhtml

# Pull Request

Updated code of conduct and CONTRIBUTIONS.md

2023-12-14 07:17 UTC, aramshiva approved these changes

2023-12-18 19:12 UTC, jdogcoder commented on CONTRIBUTING.md
> +<!-- omit in toc -->
?

2023-12-18 19:13 UTC, jdogcoder requested changes

2023-12-18 19:13 UTC, jdogcoder commented on CONTRIBUTING.md
> +<!-- omit in toc -->
@kcoderhtml these are everwhere, should they be?

2023-12-18 19:18 UTC, kcoderhtml commented on CONTRIBUTING.md
> +<!-- omit in toc -->
not sure but they do seem to omit that heading from the toc

2023-12-21 14:33 UTC, jdogcoder approved these changes

2023-12-21 14:33 UTC, merged